// Generated by CoffeeScript 1.10.0
var MenuView, menuView,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

MenuView = (function(superClass) {
  extend(MenuView, superClass);

  function MenuView() {
    this.render = bind(this.render, this);
    return MenuView.__super__.constructor.apply(this, arguments);
  }

  MenuView.prototype.el = "#menu-panel";

  MenuView.prototype.tagName = "div";

  MenuView.prototype.initialize = function() {
    return console.log("Menu View Initialized");
  };

  MenuView.prototype.render = function() {
    $.get("/bb/templates/menu.html", (function(_this) {
      return function(data) {
        return _this.$el.html(data);
      };
    })(this), "html");
    return this;
  };

  return MenuView;

})(Backbone.View);

menuView = new MenuView;
