// Generated by CoffeeScript 1.10.0
var Slider, SliderItem,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

SliderItem = (function(superClass) {
  extend(SliderItem, superClass);

  function SliderItem() {
    return SliderItem.__super__.constructor.apply(this, arguments);
  }

  return SliderItem;

})(Backbone.Model);

Slider = (function(superClass) {
  extend(Slider, superClass);

  function Slider() {
    return Slider.__super__.constructor.apply(this, arguments);
  }

  Slider.prototype.model = SliderItem;

  Slider.prototype.url = "backend.php";

  return Slider;

})(Backbone.Collection);
